# Generated by Django 2.2.2 on 2019-07-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblogmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
